#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/proprietary_financial_data"
require "net/ddex/xml/v20100712/ddexc/calculation_type"
require "net/ddex/xml/v20100712/ddexc/deal_reference"
require "net/ddex/xml/v20100712/ddexc/deduction_rate"
require "net/ddex/xml/v20100712/ddexc/price_information"
require "net/ddex/xml/v20100712/ddexc/promotional_code"
require "net/ddex/xml/v20100712/ddexc/tax_rate"
require "net/ddex/xml/v20100712/ddexc/technical_instantiation"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::DetailedDeal < Element
  include ROXML


  xml_name "ns1:DetailedDeal"

      xml_accessor :currency_code, :from => "CurrencyCode", :required => false
      xml_accessor :price_information, :as => Net::Ddex::Xml::V20100712::Ddexc::PriceInformation, :from => "PriceInformation", :required => false
      xml_accessor :promotional_code, :as => Net::Ddex::Xml::V20100712::Ddexc::PromotionalCode, :from => "PromotionalCode", :required => false
      xml_accessor :promotional?, :from => "IsPromotional", :required => false
      xml_accessor :deal_reference, :as => Net::Ddex::Xml::V20100712::Ddexc::DealReference, :from => "DealReference", :required => false
      xml_accessor :tax_rates, :as => [Net::Ddex::Xml::V20100712::Ddexc::TaxRate], :from => "TaxRate", :required => false
      xml_accessor :price_consumer_paid_exc_sales_tax, :as => Float, :from => "PriceConsumerPaidExcSalesTax", :required => false
      xml_accessor :calculation_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CalculationType], :from => "CalculationType", :required => false
      xml_accessor :royalty_rate_type, :from => "RoyaltyRateType", :required => false
      xml_accessor :royalty_rate, :as => Float, :from => "RoyaltyRate", :required => false
      xml_accessor :agreed_unit_price_exc_sales_tax, :as => Float, :from => "AgreedUnitPriceExcSalesTax", :required => false
      xml_accessor :deduction_rates, :as => [Net::Ddex::Xml::V20100712::Ddexc::DeductionRate], :from => "DeductionRate", :required => false
      xml_accessor :effective_unit_royalty_rate_net, :as => Float, :from => "EffectiveUnitRoyaltyRateNet", :required => false
      xml_accessor :proprietary_financial_datas, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::ProprietaryFinancialData], :from => "ProprietaryFinancialData", :required => false
      xml_accessor :amount_payable, :as => Float, :from => "AmountPayable", :required => false
      xml_accessor :amount_payable_in_currency_of_accounting, :as => Float, :from => "AmountPayableInCurrencyOfAccounting", :required => false
      xml_accessor :currency_exchange_rate, :as => Float, :from => "CurrencyExchangeRate", :required => false
      xml_accessor :technical_instantiation, :as => Net::Ddex::Xml::V20100712::Ddexc::TechnicalInstantiation, :from => "TechnicalInstantiation", :required => false


  

end

end end end end end end
