#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/sales_report_message_reference"
require "net/ddex/xml/v20100712/ddexc/applied_royalty_rate"
require "net/ddex/xml/v20100712/ddexc/period"
require "net/ddex/xml/v20100712/ddexc/price"
require "net/ddex/xml/v20100712/ddexc/proprietary_id"
require "net/ddex/xml/v20100712/ddexc/release_id"
require "net/ddex/xml/v20100712/ddexc/rights_agreement_id"
require "net/ddex/xml/v20100712/ddexc/rights_type"
require "net/ddex/xml/v20100712/ddexc/royalty_amount"
require "net/ddex/xml/v20100712/ddexc/tariff_reference"
require "net/ddex/xml/v20100712/ddexc/tax"
require "net/ddex/xml/v20100712/ddexc/use_type"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::InvoiceItem < Element
  include ROXML


  xml_name "ns1:InvoiceItem"

      xml_accessor :invoice_item_id, :as => Net::Ddex::Xml::V20100712::Ddexc::ProprietaryId, :from => "InvoiceItemId", :required => true
      xml_accessor :license_or_claim_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::RightsAgreementId], :from => "LicenseOrClaimId", :required => false
      xml_accessor :invoice_period, :as => Net::Ddex::Xml::V20100712::Ddexc::Period, :from => "InvoicePeriod", :required => true
      xml_accessor :sales_report_message_references, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::SalesReportMessageReference], :from => "SalesReportMessageReference", :required => false
      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseId], :from => "ReleaseId", :required => false
      xml_accessor :number_of_usages, :as => Integer, :from => "NumberOfUsages", :required => true
      xml_accessor :release_usage_price, :as => Net::Ddex::Xml::V20100712::Ddexc::Price, :from => "ReleaseUsagePrice", :required => true
      xml_accessor :applied_tariff, :as => Net::Ddex::Xml::V20100712::Ddexc::TariffReference, :from => "AppliedTariff", :required => false
      xml_accessor :applied_royalty_rate, :as => Net::Ddex::Xml::V20100712::Ddexc::AppliedRoyaltyRate, :from => "AppliedRoyaltyRate", :required => true
      xml_accessor :calculated_royalty_amount_per_use, :as => Net::Ddex::Xml::V20100712::Ddexc::RoyaltyAmount, :from => "CalculatedRoyaltyAmountPerUse", :required => true
      xml_accessor :calculated_taxes, :as => [Net::Ddex::Xml::V20100712::Ddexc::Tax], :from => "CalculatedTax", :required => false
      xml_accessor :calculated_royalty_amount_per_invoice, :as => Net::Ddex::Xml::V20100712::Ddexc::RoyaltyAmount, :from => "CalculatedRoyaltyAmountPerInvoice", :required => true
      xml_accessor :rights_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::RightsType], :from => "RightsType", :required => false
      xml_accessor :release_types, :as => [], :from => "ReleaseType", :required => false
      xml_accessor :use_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UseType], :from => "UseType", :required => false


  

end

end end end end end end
