#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/description"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::ProprietaryFinancialData < Element
  include ROXML


  xml_name "ns1:ProprietaryFinancialData"

      xml_accessor :value, :as => Float, :from => "Value", :required => true
      xml_accessor :description, :as => Net::Ddex::Xml::V20100712::Ddexc::Description, :from => "Description", :required => false


  

end

end end end end end end
