#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/c_line"
require "net/ddex/xml/v20100712/ddexc/event_date"
require "net/ddex/xml/v20100712/ddexc/p_line"
require "net/ddex/xml/v20100712/ddexc/reference_title"
require "net/ddex/xml/v20100712/ddexc/release_collection_reference"
require "net/ddex/xml/v20100712/ddexc/release_details_by_territory"
require "net/ddex/xml/v20100712/ddexc/release_id"
require "net/ddex/xml/v20100712/ddexc/release_resource_reference_list"
require "net/ddex/xml/v20100712/ddexc/release_type"
require "net/ddex/xml/v20100712/ddexc/rights_agreement_id"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::Release < Element
  include ROXML


  xml_name "ns1:Release"

      xml_accessor :release_ids, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseId], :from => "ReleaseId", :required => true
      xml_accessor :reference_title, :as => Net::Ddex::Xml::V20100712::Ddexc::ReferenceTitle, :from => "ReferenceTitle", :required => true
      xml_accessor :release_resource_reference_list, :as => Net::Ddex::Xml::V20100712::Ddexc::ReleaseResourceReferenceList, :from => "ReleaseResourceReferenceList", :required => false
      xml_accessor :release_collection_references, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseCollectionReference], :from => "ReleaseCollectionReference", :required => false
      xml_accessor :release_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :release_details_by_territories, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseDetailsByTerritory], :from => "ReleaseDetailsByTerritory", :required => true
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :duration_of_musical_content, :from => "DurationOfMusicalContent", :required => false
      xml_accessor :rights_agreement_id, :as => Net::Ddex::Xml::V20100712::Ddexc::RightsAgreementId, :from => "RightsAgreementId", :required => false
      xml_accessor :p_lines, :as => [Net::Ddex::Xml::V20100712::Ddexc::PLine], :from => "PLine", :required => false
      xml_accessor :c_lines, :as => [Net::Ddex::Xml::V20100712::Ddexc::CLine], :from => "CLine", :required => false
      xml_accessor :url, :from => "URL", :required => false
      xml_accessor :creation_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "CreationDate", :required => false
      xml_accessor :original_release_date, :as => Net::Ddex::Xml::V20100712::Ddexc::EventDate, :from => "OriginalReleaseDate", :required => false
      xml_accessor :original_language, :from => "OriginalLanguage", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end end
