#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/sales_report_to_record_company"
require "net/ddex/xml/v2010/dsr_main/v32/total_sales_by_release_type"
require "net/ddex/xml/v20100712/ddexc/contained_release_summary"
require "net/ddex/xml/v20100712/ddexc/message_header"
require "net/ddex/xml/v20100712/ddexc/message_notification_period"
require "net/ddex/xml/v20100712/ddexc/remittance_advice"
require "net/ddex/xml/v20100712/ddexc/royalty_amount"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SalesReportToRecordCompanyMessage < Element
  include ROXML

    setns "ns1", "http://ddex.net/xml/2010/dsr-main/32"

  xml_name "ns1:SalesReportToRecordCompanyMessage"

      xml_accessor :message_header, :as => Net::Ddex::Xml::V20100712::Ddexc::MessageHeader, :from => "MessageHeader", :required => true
      xml_accessor :message_notification_period, :as => Net::Ddex::Xml::V20100712::Ddexc::MessageNotificationPeriod, :from => "MessageNotificationPeriod", :required => true
      xml_accessor :remittance_advice, :as => Net::Ddex::Xml::V20100712::Ddexc::RemittanceAdvice, :from => "RemittanceAdvice", :required => false
      xml_accessor :message_content_revenue_type, :from => "MessageContentRevenueType", :required => false
      xml_accessor :rights_coverages, :as => [], :from => "RightsCoverage", :required => false
      xml_accessor :contained_release_summaries, :as => [Net::Ddex::Xml::V20100712::Ddexc::ContainedReleaseSummary], :from => "ContainedReleaseSummary", :required => false
      xml_accessor :sales_reports, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::SalesReportToRecordCompany], :from => "SalesReport", :required => false
      xml_accessor :total_sales_by_release_types, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::TotalSalesByReleaseType], :from => "TotalSalesByReleaseType", :required => true
      xml_accessor :royalty_amount, :as => Net::Ddex::Xml::V20100712::Ddexc::RoyaltyAmount, :from => "RoyaltyAmount", :required => false
      xml_accessor :number_of_sales_transaction_records, :as => Integer, :from => "NumberOfSalesTransactionRecords", :required => false


  
      xml_accessor :message_schema_version_id, :from => "@MessageSchemaVersionId", :required => true
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end end
