#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/sales_to_record_company_by_commercial_model"
require "net/ddex/xml/v20100712/ddexc/dsp"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SalesReportToRecordCompany < Element
  include ROXML


  xml_name "ns1:SalesReportToRecordCompany"

      xml_accessor :dsp, :as => Net::Ddex::Xml::V20100712::Ddexc::DSP, :from => "DSP", :required => true
      xml_accessor :sales_by_commercial_models, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::SalesToRecordCompanyByCommercialModel], :from => "SalesByCommercialModel", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end end
