#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SalesReportMessageReference < Element
  include ROXML


  xml_name "ns1:SalesReportMessageReference"

      xml_accessor :message_id, :from => "MessageId", :required => true
      xml_accessor :message_thread_id, :from => "MessageThreadId", :required => true


  

end

end end end end end end
