#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/deal_for_record_companies"
require "net/ddex/xml/v2010/dsr_main/v32/sales_data_to_record_company"
require "net/ddex/xml/v20100712/ddexc/carrier_type"
require "net/ddex/xml/v20100712/ddexc/distribution_channel_type"
require "net/ddex/xml/v20100712/ddexc/use_type"
require "net/ddex/xml/v20100712/ddexc/user_interface_type"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SalesTransactionToRecordCompany < Element
  include ROXML


  xml_name "ns1:SalesTransactionToRecordCompany"

      xml_accessor :use_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UseType], :from => "UseType", :required => true
      xml_accessor :user_interface_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UserInterfaceType], :from => "UserInterfaceType", :required => false
      xml_accessor :distribution_channel_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::DistributionChannelType], :from => "DistributionChannelType", :required => false
      xml_accessor :carrier_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CarrierType], :from => "CarrierType", :required => false
      xml_accessor :deal, :as => Net::Ddex::Xml::V2010::DsrMain::V32::DealForRecordCompanies, :from => "Deal", :required => false
      xml_accessor :sales_datas, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::SalesDataToRecordCompany], :from => "SalesData", :required => true
      xml_accessor :upgrade?, :from => "IsUpgrade", :required => false
      xml_accessor :data_to_be_forwarded?, :from => "DataToBeForwarded", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end end
