#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/deal_for_societies"
require "net/ddex/xml/v20100712/ddexc/description"
require "net/ddex/xml/v20100712/ddexc/store_location_descriptor"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SalesDataGroupingToSociety < Element
  include ROXML


  xml_name "ns1:SalesDataGroupingToSociety"

      xml_accessor :start_date, :as => Date, :from => "StartDate", :required => false
      xml_accessor :end_date, :as => Date, :from => "EndDate", :required => false
      xml_accessor :post_codes, :as => [], :from => "PostCode", :required => false
      xml_accessor :minimum_duration, :from => "MinimumDuration", :required => false
      xml_accessor :maximum_duration, :from => "MaximumDuration", :required => false
      xml_accessor :distribution_channel_types, :as => [], :from => "DistributionChannelType", :required => false
      xml_accessor :customer_ids, :as => [], :from => "CustomerId", :required => false
      xml_accessor :transaction_id, :from => "TransactionId", :required => false
      xml_accessor :store_location_descriptor, :as => Net::Ddex::Xml::V20100712::Ddexc::StoreLocationDescriptor, :from => "StoreLocationDescriptor", :required => false
      xml_accessor :promotional_activity_description, :as => Net::Ddex::Xml::V20100712::Ddexc::Description, :from => "PromotionalActivityDescription", :required => false
      xml_accessor :deal, :as => Net::Ddex::Xml::V2010::DsrMain::V32::DealForSocieties, :from => "Deal", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end end
