#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v2010/dsr_main/v32/sales_to_society_by_territory"
require "net/ddex/xml/v20100712/ddexc/commercial_model_type"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SalesToSocietyByCommercialModel < Element
  include ROXML


  xml_name "ns1:SalesToSocietyByCommercialModel"

      xml_accessor :commercial_model_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::CommercialModelType], :from => "CommercialModelType", :required => false
      xml_accessor :currency_of_accounting, :from => "CurrencyOfAccounting", :required => true
      xml_accessor :sales_by_territories, :as => [Net::Ddex::Xml::V2010::DsrMain::V32::SalesToSocietyByTerritory], :from => "SalesByTerritory", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end end end end
