#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::SummaryDeal < Element
  include ROXML


  xml_name "ns1:SummaryDeal"

      xml_accessor :currency_code, :from => "CurrencyCode", :required => false
      xml_accessor :price_consumer_paid_exc_sales_tax, :as => Float, :from => "PriceConsumerPaidExcSalesTax", :required => false
      xml_accessor :consumer_price_gross, :as => Float, :from => "ConsumerPriceGross", :required => false


  

end

end end end end end end
