#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/total_royalty_amount"
require "net/ddex/xml/v20100712/ddexc/use_type"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::TotalRoyaltyAmount < Net::Ddex::Xml::V20100712::Ddexc::TotalRoyaltyAmount
  include ROXML


  xml_name "ns1:TotalRoyaltyAmount"

      xml_accessor :use_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::UseType], :from => "UseType", :required => false


  

end

end end end end end end
