#
# Auto-generated by jaxb2ruby v0.0.1 on 2015-04-29 13:14:02 -0300
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "net/ddex/xml/v20100712/ddexc/release_type"

module Net module Ddex module Xml module V2010 module DsrMain module V32  # :nodoc: all

class Net::Ddex::Xml::V2010::DsrMain::V32::TotalSalesByReleaseType < Element
  include ROXML


  xml_name "ns1:TotalSalesByReleaseType"

      xml_accessor :release_types, :as => [Net::Ddex::Xml::V20100712::Ddexc::ReleaseType], :from => "ReleaseType", :required => false
      xml_accessor :units_sold_total, :as => Integer, :from => "UnitsSoldTotal", :required => true


  

end

end end end end end end
